apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yaml
  - deployment.yaml

namespace: default

images:
  - name: backend
    newName: backend
    newTag: latest
