server {
    listen 3000;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /movies {
        proxy_pass http://backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        try_files $uri /index.html;
    }
}