name: Backend Continuous Integration

on:
  pull_request:
    branches: [ main, master ]
    paths:
      - 'starter/backend/**'
      - '.github/workflows/backend-ci.yaml'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'
        cache-dependency-path: './starter/backend/Pipfile.lock'

    - name: Install pipenv
      run: pip install pipenv

    - name: Install dependencies
      run: pipenv install --dev

    - name: Run linter
      run: pipenv run lint

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'
        cache-dependency-path: './starter/backend/Pipfile.lock'

    - name: Install pipenv
      run: pip install pipenv

    - name: Install dependencies
      run: pipenv install --dev

    - name: Run tests
      run: pipenv run test

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build --tag mp-backend:latest .