name: Frontend Continuous Integration

on:
  pull_request:
    branches: [main]
    paths:
      - 'starter/frontend/**'
      - '.github/workflows/frontend-ci.yaml'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: starter/frontend/.nvmrc
          cache: npm
          cache-dependency-path: starter/frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run npm run lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: starter/frontend/.nvmrc
          cache: npm
          cache-dependency-path: starter/frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run npm run test
        run: npm test -- --watchAll=false
        env:
          CI: true

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build application using Docker
        uses: docker/build-push-action@v6
        with:
          context: starter/frontend
          push: false
          tags: mp-frontend:${{ github.sha }}
          build-args: |
            REACT_APP_MOVIE_API_URL=http://localhost:5000

