name: Frontend Continuous Integration

on:
  push:
    branches:
      - master
    paths:
      - "starter/frontend/**"
      - ".github/workflows/frontend-ci.yaml"

  pull_request:
    branches:
      - main
    paths:
      - "starter/frontend/**"
      - ".github/workflows/frontend-ci.yaml"

  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: starter/frontend/package-lock.json

      - name: Install dependencies
        working-directory: starter/frontend
        run: npm ci

      - name: Run lint
        working-directory: starter/frontend
        run: npm run lint

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: starter/frontend/package-lock.json

      - name: Install dependencies
        working-directory: starter/frontend
        run: npm ci

      - name: Run tests
        working-directory: starter/frontend
        run: CI=true npm test

  build:
    name: Build
    needs:
      - lint
      - test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: starter/frontend/package-lock.json

      - name: Install dependencies
        working-directory: starter/frontend
        run: npm ci

      - name: Run tests
        working-directory: starter/frontend
        run: CI=true npm test

      - name: Build Docker image
        working-directory: starter/frontend
        env:
          REACT_APP_MOVIE_API_URL: http://localhost:5000
        run: |
          docker build \
            --build-arg REACT_APP_MOVIE_API_URL=$REACT_APP_MOVIE_API_URL \
            --tag mp-frontend:latest .